# Server Port
server.port=8081

# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://shashinaupa:1234567890@cluster0.66r9hkd.mongodb.net/?appName=Cluster0

# Swagger UI Configurations
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html